// <auto-generated />
using System;
using Eliboo.Infrastructure.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Eliboo.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("BookUser", b =>
                {
                    b.Property<int>("BooksId")
                        .HasColumnType("integer")
                        .HasColumnName("books_id");

                    b.Property<int>("UsersId")
                        .HasColumnType("integer")
                        .HasColumnName("users_id");

                    b.HasKey("BooksId", "UsersId")
                        .HasName("pk_my_list");

                    b.HasIndex("UsersId")
                        .HasDatabaseName("ix_my_list_users_id");

                    b.ToTable("my_list");
                });

            modelBuilder.Entity("Eliboo.Domain.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("author");

                    b.Property<int>("BookshelfId")
                        .HasColumnType("integer")
                        .HasColumnName("bookshelf_id");

                    b.Property<string>("Genre")
                        .HasColumnType("text")
                        .HasColumnName("genre");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_books");

                    b.HasIndex("BookshelfId")
                        .HasDatabaseName("ix_books_bookshelf_id");

                    b.ToTable("books");
                });

            modelBuilder.Entity("Eliboo.Domain.Entities.Bookshelf", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("description");

                    b.Property<int>("LibraryId")
                        .HasColumnType("integer")
                        .HasColumnName("library_id");

                    b.HasKey("Id")
                        .HasName("pk_bookshelves");

                    b.HasIndex("LibraryId", "Description")
                        .IsUnique()
                        .HasDatabaseName("ix_bookshelves_library_id_description");

                    b.ToTable("bookshelves");
                });

            modelBuilder.Entity("Eliboo.Domain.Entities.Library", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("access_token");

                    b.HasKey("Id")
                        .HasName("pk_libraries");

                    b.HasIndex("AccessToken")
                        .IsUnique()
                        .HasDatabaseName("ix_libraries_access_token");

                    b.ToTable("libraries");
                });

            modelBuilder.Entity("Eliboo.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CurrentReadingId")
                        .HasColumnType("integer")
                        .HasColumnName("current_reading_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("email");

                    b.Property<int>("LibraryId")
                        .HasColumnType("integer")
                        .HasColumnName("library_id");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("password");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("CurrentReadingId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_current_reading_id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("LibraryId")
                        .HasDatabaseName("ix_users_library_id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users");
                });

            modelBuilder.Entity("BookUser", b =>
                {
                    b.HasOne("Eliboo.Domain.Entities.Book", null)
                        .WithMany()
                        .HasForeignKey("BooksId")
                        .HasConstraintName("fk_my_list_books_books_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eliboo.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .HasConstraintName("fk_my_list_users_users_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Eliboo.Domain.Entities.Book", b =>
                {
                    b.HasOne("Eliboo.Domain.Entities.Bookshelf", "Bookshelf")
                        .WithMany("Books")
                        .HasForeignKey("BookshelfId")
                        .HasConstraintName("fk_books_bookshelves_bookshelf_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bookshelf");
                });

            modelBuilder.Entity("Eliboo.Domain.Entities.Bookshelf", b =>
                {
                    b.HasOne("Eliboo.Domain.Entities.Library", "Library")
                        .WithMany("Bookshelves")
                        .HasForeignKey("LibraryId")
                        .HasConstraintName("fk_bookshelves_libraries_library_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Library");
                });

            modelBuilder.Entity("Eliboo.Domain.Entities.User", b =>
                {
                    b.HasOne("Eliboo.Domain.Entities.Book", "CurrentReading")
                        .WithOne("User")
                        .HasForeignKey("Eliboo.Domain.Entities.User", "CurrentReadingId")
                        .HasConstraintName("fk_users_books_current_reading_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Eliboo.Domain.Entities.Library", "Library")
                        .WithMany("Users")
                        .HasForeignKey("LibraryId")
                        .HasConstraintName("fk_users_libraries_library_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentReading");

                    b.Navigation("Library");
                });

            modelBuilder.Entity("Eliboo.Domain.Entities.Book", b =>
                {
                    b.Navigation("User");
                });

            modelBuilder.Entity("Eliboo.Domain.Entities.Bookshelf", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Eliboo.Domain.Entities.Library", b =>
                {
                    b.Navigation("Bookshelves");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
