// <auto-generated />
using System;
using Eliboo.Data.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Eliboo.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210208131841_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("BookUser", b =>
                {
                    b.Property<int>("BooksId")
                        .HasColumnType("integer")
                        .HasColumnName("books_id");

                    b.Property<int>("UsersId")
                        .HasColumnType("integer")
                        .HasColumnName("users_id");

                    b.HasKey("BooksId", "UsersId")
                        .HasName("pk_my_list");

                    b.HasIndex("UsersId")
                        .HasDatabaseName("ix_my_list_users_id");

                    b.ToTable("my_list");
                });

            modelBuilder.Entity("Eliboo.Data.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("author");

                    b.Property<int>("BookshelfId")
                        .HasColumnType("integer")
                        .HasColumnName("bookshelf_id");

                    b.Property<string>("Genre")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("genre");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_books");

                    b.HasIndex("BookshelfId")
                        .HasDatabaseName("ix_books_bookshelf_id");

                    b.ToTable("books");
                });

            modelBuilder.Entity("Eliboo.Data.Entities.Bookshelf", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("description");

                    b.Property<int>("LibraryId")
                        .HasColumnType("integer")
                        .HasColumnName("library_id");

                    b.HasKey("Id")
                        .HasName("pk_bookshelves");

                    b.HasIndex("LibraryId")
                        .HasDatabaseName("ix_bookshelves_library_id");

                    b.ToTable("bookshelves");
                });

            modelBuilder.Entity("Eliboo.Data.Entities.Library", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("access_token");

                    b.HasKey("Id")
                        .HasName("pk_libraries");

                    b.ToTable("libraries");
                });

            modelBuilder.Entity("Eliboo.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .UseIdentityByDefaultColumn();

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("email");

                    b.Property<int>("LibraryId")
                        .HasColumnType("integer")
                        .HasColumnName("library_id");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("nickname");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("password");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("LibraryId")
                        .HasDatabaseName("ix_users_library_id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("BookUser", b =>
                {
                    b.HasOne("Eliboo.Data.Entities.Book", null)
                        .WithMany()
                        .HasForeignKey("BooksId")
                        .HasConstraintName("fk_my_list_books_books_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eliboo.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .HasConstraintName("fk_my_list_users_users_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Eliboo.Data.Entities.Book", b =>
                {
                    b.HasOne("Eliboo.Data.Entities.Bookshelf", "Bookshelf")
                        .WithMany("Books")
                        .HasForeignKey("BookshelfId")
                        .HasConstraintName("fk_books_bookshelves_bookshelf_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bookshelf");
                });

            modelBuilder.Entity("Eliboo.Data.Entities.Bookshelf", b =>
                {
                    b.HasOne("Eliboo.Data.Entities.Library", "Library")
                        .WithMany("Bookshelves")
                        .HasForeignKey("LibraryId")
                        .HasConstraintName("fk_bookshelves_libraries_library_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Library");
                });

            modelBuilder.Entity("Eliboo.Data.Entities.User", b =>
                {
                    b.HasOne("Eliboo.Data.Entities.Library", "Library")
                        .WithMany("Users")
                        .HasForeignKey("LibraryId")
                        .HasConstraintName("fk_users_libraries_library_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Library");
                });

            modelBuilder.Entity("Eliboo.Data.Entities.Bookshelf", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Eliboo.Data.Entities.Library", b =>
                {
                    b.Navigation("Bookshelves");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
