// <auto-generated />
using System;
using Eliboo.Data.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Eliboo.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210206135447_SnakeCaseNamingConvention")]
    partial class SnakeCaseNamingConvention
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Eliboo.Data.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("author");

                    b.Property<int?>("BookshelfId")
                        .HasColumnType("integer")
                        .HasColumnName("bookshelf_id");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("genre");

                    b.HasKey("Id")
                        .HasName("pk_books");

                    b.HasIndex("BookshelfId")
                        .HasDatabaseName("ix_books_bookshelf_id");

                    b.ToTable("books");
                });

            modelBuilder.Entity("Eliboo.Data.Models.Bookshelf", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("description");

                    b.HasKey("Id")
                        .HasName("pk_bookshelves");

                    b.ToTable("bookshelves");
                });

            modelBuilder.Entity("Eliboo.Data.Models.MyList", b =>
                {
                    b.Property<int>("BooksId")
                        .HasColumnType("integer")
                        .HasColumnName("books_id");

                    b.Property<int>("UsersId")
                        .HasColumnType("integer")
                        .HasColumnName("users_id");

                    b.HasIndex("BooksId")
                        .HasDatabaseName("ix_my_list_books_id");

                    b.HasIndex("UsersId")
                        .HasDatabaseName("ix_my_list_users_id");

                    b.ToTable("my_list");
                });

            modelBuilder.Entity("Eliboo.Data.Models.ReadingNow", b =>
                {
                    b.Property<int>("BooksId")
                        .HasColumnType("integer")
                        .HasColumnName("books_id");

                    b.Property<int>("UsersId")
                        .HasColumnType("integer")
                        .HasColumnName("users_id");

                    b.HasIndex("BooksId")
                        .HasDatabaseName("ix_reading_now_books_id");

                    b.HasIndex("UsersId")
                        .HasDatabaseName("ix_reading_now_users_id");

                    b.ToTable("reading_now");
                });

            modelBuilder.Entity("Eliboo.Data.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("email");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("nickname");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("password");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Eliboo.Data.Models.Book", b =>
                {
                    b.HasOne("Eliboo.Data.Models.Bookshelf", "Bookshelf")
                        .WithMany()
                        .HasForeignKey("BookshelfId")
                        .HasConstraintName("fk_books_bookshelves_bookshelf_id");

                    b.Navigation("Bookshelf");
                });

            modelBuilder.Entity("Eliboo.Data.Models.MyList", b =>
                {
                    b.HasOne("Eliboo.Data.Models.Book", "Books")
                        .WithMany()
                        .HasForeignKey("BooksId")
                        .HasConstraintName("fk_my_list_books_books_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eliboo.Data.Models.User", "Users")
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .HasConstraintName("fk_my_list_users_users_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Books");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Eliboo.Data.Models.ReadingNow", b =>
                {
                    b.HasOne("Eliboo.Data.Models.Book", "Books")
                        .WithMany()
                        .HasForeignKey("BooksId")
                        .HasConstraintName("fk_reading_now_books_books_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eliboo.Data.Models.User", "Users")
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .HasConstraintName("fk_reading_now_users_users_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Books");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
